version: "3.8"
services:
  frst-dash:
    build: .
    ports:
      - "4500:8080"  # Map port 8080 inside the container to port 4500 on the host
    environment:
      - PYTHONUNBUFFERED=1  # Keeps Python output unbuffered for better logging
    volumes:
      - .:/app  # Mount your local directory to the container's /app directory
    command: gunicorn -b 0.0.0.0:8080 app:server  # Run the app with Gunicorn on port 8080 inside the container
    restart: always  # Optional: restart the container automatically if it fails
